### PR TITLE
Sync dev with main

### LINKED ISSUE #332: Sync dev with main
It seems `dev` is behind few commits from `main`. `dev` branch should always be ahead x commits from main, not behind.

### PR DESCRIPTION
**Pull request by aktech**
Fixes #332

### CODE REVIEW

**Review by laisbsc — COMMENTED** [review]
LGTM. Maybe we should also update the [RELEASE.md](https://github.com/Quansight/qhub-cloud/blob/main/RELEASE.md) file with the changelog for the release.

What do you think?

**Comment by aktech** [comment]
> LGTM. Maybe we should also update the RELEASE.md file with the changelog for the release.

Yes, we should definitely. But this is beyond the scope of this PR as it just merges commits from `main` into `dev`

Screenshot 2021-02-25 at 13 07 18

**Comment by laisbsc** [comment]
Alright! Sorry about that and consider it approved then :)

**Review by laisbsc — APPROVED** [review]

**Comment by aktech** [comment]
> Alright! Sorry about that and consider it approved then :)

Thanks for reviewing, nothing to be apologetic here, that's a good suggestion, we should update `RELEASE.md` soon.

**Pull request merged**
