### PR TITLE
Remove terraform as an install dependency

### PR DESCRIPTION
**Pull request by costrouc**
Side effect of this PR is that the user of qhub no longer controls the terraform version used. Instead a terraform binary is installed automatically with any terraform commands.

Closes https://github.com/Quansight/qhub-cloud/issues/289

### CODE REVIEW

**Review by aktech — COMMENTED** [review]
This looks great! @costrouc 

You have removed config files from the asset, I don't recall where were they used?

**Comment by costrouc** [comment]
> You have removed config files from the asset, I don't recall where were they used?

Yeah they are no longer used or reffered to. `qhub init` made them not needed as they were examples of how to configure qhub. documentation also addressses the purpose of these files.

**Comment by costrouc** [comment]
The curl backoff worked and has made the tests for resilient https://github.com/Quansight/qhub-cloud/pull/417/checks?check_run_id=2179731674#step:18:1.

**Comment by costrouc** [comment]
Ready for merge

**Comment by costrouc** [comment]
@aktech or @tylerpotts pinging for review

**Review by aktech — APPROVED** [review]

**Pull request merged**
