### PR TITLE
include coc link on readme.md

### LINKED ISSUE #277: Add/Link CoC and inclusivity documents
@trallard noticed that we don't have CoC/Inclusivity docs linked/added in the repos, it would be great to add them. Quoting Tania:

> - Add the Quansight CoC to the qhub repos or at least add a link to it. Having this visible is critical for our community health and safety.
> - Add an inclusivity doc (like the Kubeflow) to help with our community standards for the get go

### PR DESCRIPTION
**Pull request by laisbsc**
Added the Code of Conduct to the README.md as required by Tania and Dharhas.

The next step is to write an inclusivity document, such as the one on [Kubleflow](https://github.com/kubeflow/community/blob/master/INCLUSIVITY.md) to help with our community standards for the get-go.

Addresses part of #277.

### CODE REVIEW

**Comment by aktech** [comment]
Looks good!

**Comment by laisbsc** [comment]
So review me with a glorious 👍🏽  so I can merge this baby.

**Comment by aktech** [comment]
I thought you're going to include the Inclusivity in this PR. If not I would suggest to remove the following line from the description:

> Closes #277.

As it will close #277 automatically and #277 should only be closed when Inclusivity is added as well (not necessarily in this PR though)

**Review by aktech — APPROVED** [review]

**Comment by laisbsc** [comment]
The inclusivity seems like a very low priority right now so I was just going to close it. But you're right. Let's do the whole thing.

**Pull request merged**
