### PR TITLE
Dask Gateway 0.9.0

### PR DESCRIPTION
**Pull request by brl0**

### CODE REVIEW

**Comment by brl0** [comment]
Related to https://github.com/Quansight/qhub-terraform-modules/pull/37

**Comment by tylerpotts** [comment]
@brl0 Did you verify that this works on a running kubernetes cluster in the cloud?

**Comment by brl0** [comment]
@tylerpotts, I have not tested in the cloud yet, so far I have only tested using kubernetes in docker (kind).  Everything seems to be working properly, except for the dashboard.  I would really appreciate some help troubleshooting this last issue.  I feel pretty confident this is the last remaining issue because everything else seems to be working after a lengthy process of changes through trial and error.

It should be noted that the qhub-dask-worker image will need to be updated for this to work.  Dask gateway launches the scheduler using a command `dask-scheduler --host "" --other-options etc`... note the empty string following the host parameter.  When trying to launch the dask-scheduler via `conda run`, conda does not pass the empty string correctly on the command line.  It is therefore necessary to activate the desired environment before running `dask-scheduler` or `dask-worker`.  The qhub-dask-worker postBuild script was updated accordingly.  I wanted to share this because building this image is a prerequisite for testing.

**Comment by brl0** [comment]
@tylerpotts, I finally got everything working correctly.  I was able to get the dashboard working by configuring it as a hub service borrowing config from [here](https://github.com/pangeo-data/pangeo-cloud-federation/issues/584#issuecomment-622510533).

What are the next steps to get this tested, reviewed, and hopefully merged?

**Comment by aktech** [comment]
@brl0 Thanks for putting the effort for getting all this, I plan to look at your PRs by the end of this week.

**Comment by aktech** [comment]
@brl0 We now merge in `dev` branch, I have changed the base branch for this PR, I'll fix the conflicts in a sec.

**Comment by aktech** [comment]
> I have changed the base branch for this PR, I'll fix the conflicts in a sec.

Also, after this we will be able to test it in the CI (thanks to the recent addition of local testing.)

**Comment by dharhas** [comment]
@rsignell-usgs thought this PR might spark joy :)

**Comment by aktech** [comment]
@brl0 Jupyterlab Image is not building properly at the moment:

https://github.com/Quansight/qhub-cloud/runs/1987130002?check_suite_focus=true

Having a look.

**Comment by brl0** [comment]
@aktech, The jupyterlab image is not building properly because it is installing jupyterlab 3 and then attempting to install jupyterlab extensions directly, but now most of those extensions should actually be installed via conda or pip for `jupyterlab >= 3`.

Here is the error:
```
ValueError: The extension "@pyviz/jupyterlab_pyviz" does not yet support the current version of JupyterLab.
```

I also submitted PR #319 to update the jupyterlab image, which fixes the issue.

This PR does not modify the jupyterlab Dockerfile so it didn't cause the issue to arise, but happy to help address it however is most appropriate.

**Comment by aktech** [comment]
Hey @brl0 thanks for letting me know, I'll get that (https://github.com/Quansight/qhub-cloud/pull/319) merged asap and then we can rebase this PR on top of it.

**Comment by costrouc** [comment]
The PR looks good but we still need to do testing in the cloud (there were some issue with the recent traaefik deployment unrelated to this PR).

**Comment by brl0** [comment]
The version of dask pinned in this PR was based on the dask-gateway [Dockerfile](https://github.com/dask/dask-gateway/blob/master/dask-gateway/Dockerfile).  However, recent versions of dask seem to be working as well based on my local testing (using kind), so these pins could probably be updated or removed.

**Comment by aktech** [comment]
@brl0 It seems you merged the wrong branch into this, we need to merge dev instead make sure to pull. I'll merge dev into it now.

**Comment by brl0** [comment]
Strange, this is what is in my `.bash_history` file:
```
git fetch upstream
git merge upstream/dev
```

**Review by aktech — APPROVED** [review]
I have tested this deployed locally and on GCP with the [latest image](https://github.com/Quansight/qhub-cloud/runs/2056417217):[54b11306e..](https://hub.docker.com/layers/140403195/quansight/qhub-jupyterlab/54b11306e5c50731dcf8fdc34811367a74892742/images/sha256-f43b70b2eed075d3e14d9dd4a68897ee489d0f67ff6ed55a2227f841bab2de0c?context=explore) built with this PR. Dask gateway seems to work fine. This looks in good shape, so I am going to merge it.

Thanks a lot @brl0 for your work. 🎉

**Pull request merged**
